#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
#
#  server:
#    eviction-interval-timer-in-ms: 1000
#server:
#  port: 8060
#
## Commented lines should be left as comments since they are not needed in the YAML format.
#
## eureka:
##   client:
##     serviceUrl:
##       defaultZone: http://localhost:8761/eureka/
#
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  application:
#    name: api-gateway
#
## server:
##   tomcat:
##     connection-timeout: 60000
#
##spring:
#  config:
#    import: optional:configserver:http://localhost:8088
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - AuthenticationFilter
#        - id: course-service
#          uri: lb://course-service
#          predicates:
#            - Path=/api/course/**
#          filters:
#            - AuthenticationFilter
